define(function (require){
	'use strict';
	return ["Chuck Norris once played The Price Is Right. The prices attempted to guess the numbers Chuck Norris was thinking of.",
	"Got debt? You’re not alone: Americans owe more than $800 billion in credit card debt.",
	"18% of people are saving more for retirement this year than last year. Smart thinking!",
	"New cars lose 45% of their value over the first four years of ownership.",
	"The average honeymoon in the U.S. costs roughly $5,000.",
	"20% of U.S. couples spent more than $30,000 on their weddings.",
	"At-home weddings typically cost 10-15% more than weddings at a separate location.",
	"If you recall three happy work-related events once a week, you’re more likely to be motivated and productive at the office.",
	"83% of people feel that regifting presents they’ve received is totally acceptable.",
	"The median salary for registered nurses is almost $65,000, and there’s a extremely high and growing demand for this position!",
	"10% of truck drivers made more than $57,000 in 2010, with relatively little education or training.",
	"1.8 million jobs in education are expected to be added between 2010 and 2020.",
	"Job openings in the health care industry are expected to grow by 33% between 2010 and 2020 — more than any other industry.",
	"One projection shows that employment will grow by 20.5 million jobs in the U.S. by 2020.",
	"Recipients get the most pleasure from receiving a present if it’s one they’ve explicitly requested. ",
	"Dog owners spent $19.1 billion on their pets in 2011. In contrast, cat owners spent only $7.4 billion.",
	"The vast majority of savvy spenders are also healthy eaters. Pass the carrots!",
	"Of the top eight stressors facing Americans, five were financial. Even more reason to take control of your money.",
	"More than 60% of employees report high levels of stress.",
	"Almost 40% of stressed-out employees say that they’re feeling the burn because their workload is increasing.",
	"Stress causes 36% of workers to waste an hour or more each day. ",
	"50% of people expect to receive a tax refund this year.",
	"62% of Americans say they rarely buy clothes that aren’t on sale.",
	"Is your partner good with money … or very bad? Thinking that a partner is bad with money increases the likelihood of divorce by 45%.",
	"63% of people who expect to receive a tax refund plan to save it or invest it.",
	"Not so smart: 1/3 of grads with student loans are late or delinquent on their first payments.",
	"14% of people who expect to receive a tax refund plan to use it on a “splurge” purchase!",
	"Paying down debt is the most common financial goal for young and employed Americans.",
	"A survey of 606 people with overdraft protection found that half didn’t even know they had it!",
	"The U.S. ranks first in the world on average household income.",
	"Does your employer match your 401(k) donations? 85% of employers do.",
	"Nearly 1/3 of parents avoid telling their children about the family’s financial situation.",
	"76% of Americans say they have more positive experiences in a day than negative ones.",
	"When was your last day off? Americans give up 226 million unused vacation days each year.",
	"Research shows that little, frequent splurges make you happier than more expensive, once-in-a-while splurges.",
	"Talk about awkward: One in three parents feel more comfortable talking to their kids about drugs, alcohol and sex than about money.",
	"70% of people have never even crunched the numbers on how much money they’ll need to retire.",
	"When’s the last time you hit the gym? Physically active people save, on average, $500 a year on health care costs.",
	"Do you negotiate? 50% of male college graduates negotiated their first salary, while only 31% of female grads did the same.",
	"Getting hit with bank fees? The average household pays $500 per year in bank fees, most of which are avoidable."];
});